spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dataServer?currentSchema=data_server
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    type: org.postgresql.ds.PGSimpleDataSource


  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creatin: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop

  main:
    allow-bean-definition-overriding: true
